apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: yxorp
  labels:
    app: yxorp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yxorp
  template:
    metadata:
      labels:
        app: yxorp
    spec:
      containers:
      - name: yxorp
        image: yxorp:0.1.0
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: yxorp
spec:
  selector:
    app: yxorp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
